## Processing the results of a psychological test (using the Pandas library)

The file `extraversion.csv` contains the results of an educational psychometric study, its purpose is to identify the relationship between a person's level of extraversion and his propensity to participate in volunteer activities.

In [1]:
import pandas as pd
import numpy as np

In [2]:
ps = pd.read_csv("extraversion.csv", encoding = "UTF-8")
ps.head()

,Unnamed: 0.1,Unnamed: 0,sex,volunteer,Q 1,Q 2,Q 3,Q 4,Q 5,Q 6,...,Q 48,Q 49,Q 50,Q 51,Q 52,Q 53,Q 54,Q 55,Q 56,Q 57
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет
2,2,3,Женский,Да,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Нет,Нет,Нет,Да,Нет,Нет
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет

The dataframe contains the following columns:

* `sex': gender of a respondent (Female, Male);
* `volunteer': regular participation in volunteer activities (Yes, No);
* `Q 1` - `Q 57`: answers to questions of the Eysenck questionnaire (Yes, No). The information about the questionnaire and the questions themselves can be found on [this](http://ipp.hse.ru/57-testytest-ajzenka-ekstraversiya-introversiya-nejrotizm ) the page.

In [3]:
print(f'The dataframe contains {ps.shape[0]} rows, {ps.shape[1]} columns.')

The dataframe contains 52 rows, 61 columns.

We rename columns `Q 1`-`Q 57` to `Q1`-`Q57`, removing spaces in the middle of the names for all the columns (if any).